// Date: 05/05/2013 17:26:22
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package pixlepix.complexmachines.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class FocalPointModel extends ModelBase
{
  //fields
    ModelRenderer VerticalSpike;
    ModelRenderer DepthSpike;
    ModelRenderer WidthSpike;
    ModelRenderer BackRight;
    ModelRenderer FrontRight;
    ModelRenderer BackLeft;
    ModelRenderer FrontLeft;
  
  public FocalPointModel()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      VerticalSpike = new ModelRenderer(this, 0, 0);
      VerticalSpike.addBox(0F, 0F, 0F, 8, 16, 8);
      VerticalSpike.setRotationPoint(-4F, 8F, -4F);
      VerticalSpike.setTextureSize(128, 128);
      VerticalSpike.mirror = true;
      setRotation(VerticalSpike, 0F, 0F, 0F);
      DepthSpike = new ModelRenderer(this, 33, 0);
      DepthSpike.addBox(0F, 0F, 0F, 8, 8, 16);
      DepthSpike.setRotationPoint(-4F, 12F, -8F);
      DepthSpike.setTextureSize(128, 128);
      DepthSpike.mirror = true;
      setRotation(DepthSpike, 0F, 0F, 0F);
      WidthSpike = new ModelRenderer(this, 0, 25);
      WidthSpike.addBox(0F, 0F, 0F, 16, 8, 8);
      WidthSpike.setRotationPoint(-8F, 12F, -4F);
      WidthSpike.setTextureSize(128, 128);
      WidthSpike.mirror = true;
      setRotation(WidthSpike, 0F, 0F, 0F);
      BackRight = new ModelRenderer(this, 82, 0);
      BackRight.addBox(0F, 0F, 0F, 3, 3, 3);
      BackRight.setRotationPoint(2F, 10.5F, 2F);
      BackRight.setTextureSize(128, 128);
      BackRight.mirror = true;
      setRotation(BackRight, 0F, 0F, 0F);
      FrontRight = new ModelRenderer(this, 82, 0);
      FrontRight.addBox(0F, 0F, 0F, 3, 3, 3);
      FrontRight.setRotationPoint(2F, 10.5F, -5F);
      FrontRight.setTextureSize(128, 128);
      FrontRight.mirror = true;
      setRotation(FrontRight, 0F, 0F, 0F);
      BackLeft = new ModelRenderer(this, 82, 0);
      BackLeft.addBox(0F, 0F, 0F, 3, 3, 3);
      BackLeft.setRotationPoint(-5F, 10.5F, 2F);
      BackLeft.setTextureSize(128, 128);
      BackLeft.mirror = true;
      setRotation(BackLeft, 0F, 0F, 0F);
      FrontLeft = new ModelRenderer(this, 82, 0);
      FrontLeft.addBox(0F, 0F, 0F, 3, 3, 3);
      FrontLeft.setRotationPoint(-5F, 10.5F, -5F);
      FrontLeft.setTextureSize(128, 128);
      FrontLeft.mirror = true;
      setRotation(FrontLeft, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    VerticalSpike.render(f5);
    DepthSpike.render(f5);
    WidthSpike.render(f5);
    BackRight.render(f5);
    FrontRight.render(f5);
    BackLeft.render(f5);
    FrontLeft.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }

}
