// Date: 05/05/2013 17:25:25
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package pixlepix.complexmachines.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class OceanGeneratorModel extends ModelBase
{
  //fields
    ModelRenderer LeftPlate;
    ModelRenderer RightPlate;
    ModelRenderer TopPlate;
    ModelRenderer BottomPlate;
    ModelRenderer BackPlate;
    ModelRenderer BackPole;
    ModelRenderer BatLeft;
    ModelRenderer BatRight;
    ModelRenderer PowerStalk;
    ModelRenderer PowerCube;
  
  public OceanGeneratorModel()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      LeftPlate = new ModelRenderer(this, 0, 23);
      LeftPlate.addBox(0F, 0F, 0F, 2, 16, 11);
      LeftPlate.setRotationPoint(-8F, 8F, -8F);
      LeftPlate.setTextureSize(128, 128);
      LeftPlate.mirror = true;
      setRotation(LeftPlate, 0F, 0F, 0F);
      RightPlate = new ModelRenderer(this, 0, 52);
      RightPlate.addBox(0F, 0F, 0F, 2, 16, 11);
      RightPlate.setRotationPoint(6F, 8F, -8F);
      RightPlate.setTextureSize(128, 128);
      RightPlate.mirror = true;
      setRotation(RightPlate, 0F, 0F, 0F);
      TopPlate = new ModelRenderer(this, 27, 33);
      TopPlate.addBox(0F, 0F, 0F, 12, 2, 11);
      TopPlate.setRotationPoint(-6F, 8F, -8F);
      TopPlate.setTextureSize(128, 128);
      TopPlate.mirror = true;
      setRotation(TopPlate, 0F, 0F, 0F);
      BottomPlate = new ModelRenderer(this, 56, 0);
      BottomPlate.addBox(0F, 0F, 0F, 12, 2, 7);
      BottomPlate.setRotationPoint(-6F, 22F, -5.933333F);
      BottomPlate.setTextureSize(128, 128);
      BottomPlate.mirror = true;
      setRotation(BottomPlate, 0F, 0F, 0F);
      BackPlate = new ModelRenderer(this, 1, 0);
      BackPlate.addBox(0F, 0F, 0F, 16, 16, 1);
      BackPlate.setRotationPoint(-8F, 8F, 2F);
      BackPlate.setTextureSize(128, 128);
      BackPlate.mirror = true;
      setRotation(BackPlate, 0F, 0F, 0F);
      BackPole = new ModelRenderer(this, 36, 0);
      BackPole.addBox(0F, 0F, 0F, 4, 15, 5);
      BackPole.setRotationPoint(-2F, 8.5F, 3F);
      BackPole.setTextureSize(128, 128);
      BackPole.mirror = true;
      setRotation(BackPole, 0F, 0F, 0F);
      BatLeft = new ModelRenderer(this, 27, 52);
      BatLeft.addBox(0F, 0F, 0F, 5, 13, 5);
      BatLeft.setRotationPoint(-6.5F, 9.5F, 2.5F);
      BatLeft.setTextureSize(128, 128);
      BatLeft.mirror = true;
      setRotation(BatLeft, 0F, 0F, 0F);
      BatRight = new ModelRenderer(this, 27, 52);
      BatRight.addBox(0F, 0F, 0F, 5, 13, 5);
      BatRight.setRotationPoint(1.5F, 9.5F, 2.5F);
      BatRight.setTextureSize(128, 128);
      BatRight.mirror = true;
      setRotation(BatRight, 0F, 0F, 0F);
      PowerStalk = new ModelRenderer(this, 36, 23);
      PowerStalk.addBox(0F, 0F, 0F, 3, 4, 3);
      PowerStalk.setRotationPoint(-1.5F, 18F, -3.5F);
      PowerStalk.setTextureSize(128, 128);
      PowerStalk.mirror = true;
      setRotation(PowerStalk, 0F, 0F, 0F);
      PowerCube = new ModelRenderer(this, 50, 21);
      PowerCube.addBox(0F, 0F, 0F, 5, 5, 5);
      PowerCube.setRotationPoint(-2.5F, 13F, -4.5F);
      PowerCube.setTextureSize(128, 128);
      PowerCube.mirror = true;
      setRotation(PowerCube, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    LeftPlate.render(f5);
    RightPlate.render(f5);
    TopPlate.render(f5);
    BottomPlate.render(f5);
    BackPlate.render(f5);
    BackPole.render(f5);
    BatLeft.render(f5);
    BatRight.render(f5);
    PowerStalk.render(f5);
    PowerCube.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
