// Date: 05/05/2013 17:25:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package pixlepix.complexmachines.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class LaserEmitterModel extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer MainBack;
    ModelRenderer Bat1;
    ModelRenderer Bat2;
    ModelRenderer Bat3;
    ModelRenderer Bat4;
    ModelRenderer Focuser;
    ModelRenderer CableLeft1;
    ModelRenderer CableLeft2;
    ModelRenderer CableLeft3;
    ModelRenderer CableRight1;
    ModelRenderer CableRight2;
    ModelRenderer CableRight3;
    ModelRenderer Bump1;
    ModelRenderer Bump2;
    ModelRenderer Bump3;
  
  public LaserEmitterModel()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 16, 16, 4);
      Base.setRotationPoint(-8F, 8F, -7F);
      Base.setTextureSize(128, 128);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      MainBack = new ModelRenderer(this, 0, 21);
      MainBack.addBox(0F, 0F, 0F, 5, 15, 11);
      MainBack.setRotationPoint(-2.5F, 9F, -3F);
      MainBack.setTextureSize(128, 128);
      MainBack.mirror = true;
      setRotation(MainBack, 0F, 0F, 0F);
      Bat1 = new ModelRenderer(this, 41, 14);
      Bat1.addBox(0F, 0F, 0F, 4, 10, 4);
      Bat1.setRotationPoint(2F, 11.2F, -1.5F);
      Bat1.setTextureSize(128, 128);
      Bat1.mirror = true;
      setRotation(Bat1, 0F, 0F, 0F);
      Bat2 = new ModelRenderer(this, 41, 14);
      Bat2.addBox(0F, 0F, 0F, 4, 10, 4);
      Bat2.setRotationPoint(2F, 11.2F, 3.5F);
      Bat2.setTextureSize(128, 128);
      Bat2.mirror = true;
      setRotation(Bat2, 0F, 0F, 0F);
      Bat3 = new ModelRenderer(this, 41, 14);
      Bat3.addBox(0F, 0F, 0F, 4, 10, 4);
      Bat3.setRotationPoint(-6F, 11.2F, -1.5F);
      Bat3.setTextureSize(128, 128);
      Bat3.mirror = true;
      setRotation(Bat3, 0F, 0F, 0F);
      Bat4 = new ModelRenderer(this, 41, 14);
      Bat4.addBox(0F, 0F, 0F, 4, 10, 4);
      Bat4.setRotationPoint(-6F, 11.2F, 3.5F);
      Bat4.setTextureSize(128, 128);
      Bat4.mirror = true;
      setRotation(Bat4, 0F, 0F, 0F);
      Focuser = new ModelRenderer(this, 41, 0);
      Focuser.addBox(0F, 0F, 0F, 12, 12, 1);
      Focuser.setRotationPoint(-6F, 10F, -8F);
      Focuser.setTextureSize(128, 128);
      Focuser.mirror = true;
      setRotation(Focuser, 0F, 0F, 0F);
      CableLeft1 = new ModelRenderer(this, 68, 0);
      CableLeft1.addBox(0F, 0F, 0F, 1, 2, 1);
      CableLeft1.setRotationPoint(-5F, 9.7F, 5F);
      CableLeft1.setTextureSize(128, 128);
      CableLeft1.mirror = true;
      setRotation(CableLeft1, 0F, 0F, 0F);
      CableLeft2 = new ModelRenderer(this, 68, 0);
      CableLeft2.addBox(0F, 0F, 0F, 1, 2, 1);
      CableLeft2.setRotationPoint(-5F, 9.7F, 0F);
      CableLeft2.setTextureSize(128, 128);
      CableLeft2.mirror = true;
      setRotation(CableLeft2, 0F, 0F, 0F);
      CableLeft3 = new ModelRenderer(this, 73, 0);
      CableLeft3.addBox(0F, 0F, 0F, 1, 1, 5);
      CableLeft3.setRotationPoint(-5F, 9F, 0.5F);
      CableLeft3.setTextureSize(128, 128);
      CableLeft3.mirror = true;
      setRotation(CableLeft3, 0F, 0F, 0F);
      CableRight1 = new ModelRenderer(this, 68, 0);
      CableRight1.addBox(0F, 0F, 0F, 1, 2, 1);
      CableRight1.setRotationPoint(4F, 9.7F, 0F);
      CableRight1.setTextureSize(128, 128);
      CableRight1.mirror = true;
      setRotation(CableRight1, 0F, 0F, 0F);
      CableRight2 = new ModelRenderer(this, 68, 0);
      CableRight2.addBox(0F, 0F, 0F, 1, 2, 1);
      CableRight2.setRotationPoint(4F, 9.7F, 5F);
      CableRight2.setTextureSize(128, 128);
      CableRight2.mirror = true;
      setRotation(CableRight2, 0F, 0F, 0F);
      CableRight3 = new ModelRenderer(this, 73, 0);
      CableRight3.addBox(0F, 0F, 0F, 1, 1, 5);
      CableRight3.setRotationPoint(4F, 9F, 0.5F);
      CableRight3.setTextureSize(128, 128);
      CableRight3.mirror = true;
      setRotation(CableRight3, 0F, 0F, 0F);
      Bump1 = new ModelRenderer(this, 86, 0);
      Bump1.addBox(0F, 0F, 0F, 2, 1, 2);
      Bump1.setRotationPoint(-1F, 8F, -2F);
      Bump1.setTextureSize(128, 128);
      Bump1.mirror = true;
      setRotation(Bump1, 0F, 0F, 0F);
      Bump2 = new ModelRenderer(this, 86, 0);
      Bump2.addBox(0F, 0F, 0F, 2, 1, 2);
      Bump2.setRotationPoint(-1F, 8F, 1F);
      Bump2.setTextureSize(128, 128);
      Bump2.mirror = true;
      setRotation(Bump2, 0F, 0F, 0F);
      Bump3 = new ModelRenderer(this, 86, 0);
      Bump3.addBox(0F, 0F, 0F, 2, 1, 2);
      Bump3.setRotationPoint(-1F, 8F, 4F);
      Bump3.setTextureSize(128, 128);
      Bump3.mirror = true;
      setRotation(Bump3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    MainBack.render(f5);
    Bat1.render(f5);
    Bat2.render(f5);
    Bat3.render(f5);
    Bat4.render(f5);
    Focuser.render(f5);
    CableLeft1.render(f5);
    CableLeft2.render(f5);
    CableLeft3.render(f5);
    CableRight1.render(f5);
    CableRight2.render(f5);
    CableRight3.render(f5);
    Bump1.render(f5);
    Bump2.render(f5);
    Bump3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
