// Date: 19/05/2013 15:34:10
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package pixlepix.complexmachines.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraftforge.client.model.AdvancedModelLoader;
import net.minecraftforge.client.model.IModelCustom;

public class LaserModel extends ModelBase
{
	private IModelCustom modelTutBox;
    
    public LaserModel()
    {
        modelTutBox = AdvancedModelLoader.loadModel("/mods/ComplexMachines/models/beam.obj");
    }
    public void render()
    {
        modelTutBox.renderAll();
    }

}